### PR TITLE
[Ready] Sound browser & previewer

### PR DESCRIPTION
**Pull request by oscons**
Thanks for the recent merges @kindohm. Saw your comment about cutting a new release soon and wanted to let you know that I'm working on a "Sound Browser" type of view which would IMHO fit nicely with making a few things easier for beginners like me.

Below is the first commit, so it's not *quite* done yet. However the basics work, at least for me and on macOS. Only thing that's required at this stage is that you set the path to the `Dirt Samples` directory in the config. You should get a new View Container, likely underneath the `Extensions` container, and in there you should find your folders and samples. You can play a sample by clicking the play button right there in the tree view.

Let me know if you're interested to add this to the next release as well and I'll give it some more work.

### CODE REVIEW

**Comment by kindohm** [comment]
Great idea! Would it be possible to configure multiple sample folder paths? I usually run SuperDirt with two or three different sample folder collections. e.g. the default Dirt-Samples plus my own. I don't think this would be critical as most people probably just use one folder. But since it is possible to load multiple folders it seems like it would be good to support.

**Comment by oscons** [comment]
Yes, that's definitely possible and I've planned for this already: The config item is a string array :) As of the initial commit though only one path works properly (I think). I also planned to add an option to mark samples as "Favourites" and make them show up at the top of the list or something to that extent. Maybe I can even figure out how to pragmatically address issue #11 along the way.

Having said that, I don't want to overdo it, since it's not meant to be a sample library management tool, just a convenient way to work with SuperCollider/Tidal specific samples.

**Comment by kindohm** [comment]
Sounds good. I'm in favor of trying to limit the scope of each PR so that the changes are easier to manage. Feel free to add new issues to this repo for future ideas or enhancements to this feature, like the idea you suggested for "favorites".

**Comment by oscons** [comment]
@kindohm I've put in a bit of work for the sound browser and it's now almost feature complete for the initial version I think. "Just" needs some polishing and test cases.

If you have a couple of minutes I'd be glad if you could take a quick look and tell me what you think.

# Features
- Lists one or more user directories
- It only lists up to the second level in the specified directories to mimic what SuperDirt does
- Currently only samples on a locally accessible file system are supported
- Sample playback is handled by [node-wav-player](https://github.com/futomi/node-wav-player) and I've tested it on macOS and Linux. Unfortunately I don't have a Windows machine available at the moment
- Sound names can be copied either to the clipboard or directly to the currently active editor
- Sounds (e.g. long running loops) can be stopped by pressing `Escape` or using the button in the view title menu
- Sounds can be launched with the `Space` key, though, due to VS Code limitations, it'll play the first selected sounds, which is not necessarily the currently focused sound

## Missing features
- Refresh dos not work at the moment, changes in the file system are only picked up after restarts
- Persisting the state of expanded items is currently not working, all items will start in collapsed state
- The logo for the Tidal activity bar could probably be a little nicer.

# Other points of note:
- I had to bump up the VS Code version to ^1.30 to get clipboard access
- The icons I used are taken from [Material](https://github.com/google/material-design-icons) and manually modified. License is Apache 2.0, which is AFAIK compatible to be used in a GPLv3 project,

**Comment by kindohm** [comment]
@oscons this is great! this was super fun to play with!

Regarding the missing features, the lack of refresh was the most noticeable missing feature, but I think it is perfectly OK to add that as an enhancement later (for that matter, all of the missing features could be future enhancements). Maybe make a "requires restart" note somewhere in the readme, or in the setting description. 

Thanks for the work on this, I think this is a great addition!

Make a note here when you are ready for the PR to be merged or if you want me to take another look after any more changes.

**Comment by oscons** [comment]
Hey @kindohm, I think this is now ready to be merged. I've added a new section to the readme (737df6a ff.), added test cases (9a3b8fb) and removed the currently not working refresh commands (531016a). Let me know if there's anything else I should do. Thanks

**Comment by kindohm** [comment]
apologies for the the delay in releasing. hope to get it out very soon.

**Comment by oscons** [comment]
No worries, I'm not in a rush :)

**Comment by kindohm** [comment]
released

**Pull request merged**
