### PR TITLE
Shortcuts

### PR DESCRIPTION
**Pull request by oscons**
Hi Kindohm,

since I'm a lazy person I don't like to unnecessarily jump around the code or type out the same things over and over again. That's why I've implemented generic keyboard shortcuts for the vscode extension.

The idea is, much like with `hush`, to execute some Tidal (or rather Haskell) commands upon certain key presses. There is a bit of additional logic though that tries to determine the stream number of the statements the cursor is currently in. This allows e.g. to silence the current stream by just pressing some magic key combination, say `cmd+t+cmd+h`. Also mute, solo etc work like this.

Here's an example: Say you would execute the two statements below. Then you'd put your cursor at position 1 and execute the default shortcut 2 (mute). In the background the command `mute 1` would be sent to GHCi. Now, if you move the cursor to `position 2` and execute the default shortcut 4 (solo) the command `solo 3` would be sent.

```
d1
  $ jux rev
  $ s "hh(<3 5 7>,8)" -- position 1

d3
 $ s "bd!4" -- position 2
```

The stream number is currently determined by scanning for something that looks like `d[NUMBER]` and is on the first line of the code block and not indented. This is pretty rudimentary but probably works in 99% of all cases.

Let me know if you think this is useful and if I should amend something.

Cheers, oscons

### CODE REVIEW

**Comment by kindohm** [comment]
At first I thought that this addition wasn't very intuitive. For example, it would be easier if `ctrl+shift+1` were mapped to `d1 $ silence` and `ctrl+shift+2` were mapped to `d2 $ silence`. But, after trying out your branch and understanding how flexible the keymapping is, I like the approach you took. I'm not sure how much I would use a full set of keybindings but I think they will be useful to many others.

**Comment by oscons** [comment]
Thanks for reviewing this.

You could still map `ctrl+shift+1` the way you describe it and I can definitely see the benefits of not having to move the cursor back to a line for `d1` just to mute it.

The idea I had was however that if you're live-coding, the audience probably wants to see _something_ happening and while the shortcuts with the replacement text are still hiding what you're actually doing, at least you get a feedback on the code block you're in, so there's a visual indication that something happened.

**Comment by kindohm** [comment]
@oscons would mind taking a quick look at this merge conflict? I'm guessing we just need to take both the incoming and current changes but it would be great if you could take a look. Otherwise this looks good and I'll get it merged.

**Comment by oscons** [comment]
Thanks @kindohm. I merged the current master into this branch, so now there should be no conflicts. I've also re-read the doc I wrote and made some changes, that I hope are improving on what I had before. Finally, in c9b83be I've added another configuration option to display the generated shortcut command in the console. That way it's possible to debug the shortcuts and check if the replacements worked as as intended.

**Comment by kindohm** [comment]
@oscons thanks!

I plan on testing all of these recent changes together soon. If everything looks good we'll do the next release.

**Pull request merged**
