### PR TITLE
Refactor to TypeScript

### PR DESCRIPTION
**Pull request by rossng**
Following on from kindohm/vscode-tidalcycles/pull/13, I have fixed a lot (!) of issues in my initial pull request and written some tests. It would probably be wise to give this a good manual test before merging 😉 

I got CI working on [my fork](https://travis-ci.org/rossng/vscode-tidalcycles/branches) so you should be able to set this up pretty easily for this repository and add a build status badge to the README. I tried setting up test coverage but getting the tools to interact with VSCode's test runner is near impossible. I have an open ticket with Codecov to see if there's a solution.

Just realised I also removed the random messages functionality while refactoring - let me know if needed and I'll put that back in.

(p.s. issues don't seem to be turned on for this repository)

### CODE REVIEW

**Comment by kindohm** [comment]
thank you @rossng. I will take a look at this and manually test as soon as I get a chance.

I think it's OK that the "random message" feature was removed. That was more of a silly feature for my own amusement, but could be added back if there was demand for it.

**Comment by kindohm** [comment]
@rossng finally getting a chance to take a look at this. I got the extension running in debug mode on MacOS. A couple things I noticed with the output panel:

1. My `"tidalcycles.showOutputInConsoleChannel": true` setting doesn't seem to work. I see no Tidal output in the output panel

2. Each item in the output panel is now appended with a new line. Could a config setting be added so that the new line could be optional? I think the wrapping single line is still desirable depending on the user's preferences.

**Comment by kindohm** [comment]
when running `npm test` I am getting the error `Error: Cannot find module '../dialog'`. I haven't been able to dig in and see what might be the issue. 

```
➜  vscode-tidalcycles-real git:(rossng-master) ✗ npm run test

> vscode-tidalcycles@0.6.0 test /Users/mikehodnick/code/vscode-tidalcycles-real
> npm run compile && node ./node_modules/vscode/bin/test


> vscode-tidalcycles@0.6.0 compile /Users/mikehodnick/code/vscode-tidalcycles-real
> tsc -p ./

### VS Code Extension Test Run ###
Current working directory: /Users/mikehodnick/code/vscode-tidalcycles-real
Running extension tests: /Users/mikehodnick/code/vscode-tidalcycles-real/.vscode-test/stable/Visual Studio Code.app/Contents/MacOS/Electron /Users/mikehodnick/code/vscode-tidalcycles-real/out/test --extensionDevelopmentPath=/Users/mikehodnick/code/vscode-tidalcycles-real --extensionTestsPath=/Users/mikehodnick/code/vscode-tidalcycles-real/out/test
[main 8:07:10 AM] Running extension tests from the command line is currently only supported if no other instance of Code is running.

[main 8:07:10 AM] Error: Running extension tests from the command line is currently only supported if no other instance of Code is running.
    at /Users/mikehodnick/code/vscode-tidalcycles-real/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js:531:830
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

module.js:545
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/Users/mikehodnick/code/vscode-tidalcycles-real/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/Users/mikehodnick/code/vscode-tidalcycles-real/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/Users/mikehodnick/code/vscode-tidalcycles-real/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:383:26)

Tests exited with code: 7
```

**Comment by rossng** [comment]
1. What output are you expecting to see that isn't there? With the eval count turned off it probably won't print anything. I'm actually not sure why the GHCi prompt isn't being printed (even when flushed by a newline) so looking into that now. Actually we should think about what _should_ be printed when the user evaluates an expression: it seems to me that just printing out the GHCi prompt is not intuitive behaviour so there should at least be some kind of option.

**Comment by rossng** [comment]
2. Yes, will add that.

**Comment by rossng** [comment]
The test error is due to running tests from the command line while VS Code is running. For some reason, the VS Code test runner can't launch unless there are no instances of the application already running.

You can also run tests inside VS Code by choosing 'Tests' from the dropdown in the Debug pane.

**Comment by kindohm** [comment]
1. the GHCi prompt has traditionally been appended in the Emacs and Atom tooling on each code eval, and I think it is important to keep that at least as an option in the VS Code extension. There's a neat aesthetic quality about it, and I think it is helpful additional feedback to give to the user that the interpreter received the command successfully. I realize it might not give any functional value, but I think there is something very satisfying about seeing that prompt appended, knowing that the computer is responding.

image

**Comment by rossng** [comment]
Okay, I've changed `showGhciOutput` so that it should actually be useful now 😄 . With it enabled, it should essentially behave in the same way as it used to. With it disabled, it passes the 'zero verbosity' options to GHCi so that only actual deliberate printing (e.g. `putStrLn`) and errors are logged.

**Comment by rossng** [comment]
And this commit should ensure that `showOutputInConsoleChannel` stops _any_ GHCi output ending up in the output channel. Things like eval count are still printed.

**Comment by kindohm** [comment]
I'll review ASAP. 

aside: I have a major commitment now behind me, so I should be able to dedicate more time to this; I'd like to get this PR though as soon as we can!

**Comment by kindohm** [comment]
I'm seeing a problem when I am using a boot file in the current directory. The `finally` in this code always returns null, so the custom boot file lines are never returned. Instead, the default boot code is used instead. Since the `catch` returns, is the `finally` needed?

```
    private async getBootCommandsFromFile(uri: vscode.Uri): Promise<string[] | null> {

        this.logger.log(`Using Tidal boot file on disk at ${uri.fsPath}`);

        let doc: vscode.TextDocument;
        try {
            doc = await vscode.workspace.openTextDocument(uri); 
            return doc.getText().split(this.lineEnding);
        } catch (e) {
            this.logger.error(`Failed to load boot commands from ${uri.fsPath}`);
            return null;
        } finally {
            return null;
        }
    }
```

**Comment by rossng** [comment]
Oh wow, I didn't expect that behaviour (especially without generating a compiler error...). It should be fixed now.

**Comment by rossng** [comment]
I should probably add a couple more tests around that.

**Comment by kindohm** [comment]
I'm seeing a problem with the `bootTidalPath` setting on macOS when specifying the home directory with a `~`:

```
  "tidalcycles.bootTidalPath": "~/boot-test.hs",
```

```
Using Tidal boot file on disk at /~/boot-test.hs
Error: Failed to load boot commands from /~/boot-test.hs
```

Somehow a leading `/` is being prepended. 

When I use a full path of `/Users/mikehodnick/boot-test.hs`, it works correctly. I'm guessing this bug existed before your PR though. Unless you want to fix it, lets create a separate issue for this bug. 

Barring any last minute issues that I find during some final testing today, we should be able to merge this.

**Comment by rossng** [comment]
I'll have a look at the bug 😄

**Comment by kindohm** [comment]
Apologies for the long delay, but this has finally been published to the marketplace. Lots of excuses, like moving to MacOS, and a busy schedule, but finally got around to it. 

I've been using the new version of the extension but will keep an eye out for any issues that are reported. 

@rossng please feel free to continue with fixes and improvements! The delay in testing and publishing isn't normal for me; now that I have publishing set up on my new OS this should be a much faster process.

**Pull request merged**
